name: Create Release on Tag

on:
  push:
    tags:
      - "v*.*.*" # on every version tag will build a new android artifact.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
        
      - uses: emanuelef/wifi_test_flutter/.github/workflows/main.yml@main
